spring:
  application:
    name: auth_service

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - openid  # Use Oidc instead of OAuth
              - email   # Request email
              - profile # Request profile (name, profile picture, etc.)

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083

logging:
  level:
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.client.WebClient: DEBUG