server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: user-service
    api-prefix: /user
    services:
      pet-service: ${PET_SERVICE}
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

springdoc:
  api-docs:
    path: '${spring.application.api-prefix}/v3/api-docs'
  swagger-ui:
    operationsSorter: method
    try-it-out-enabled: true
    path: '${spring.application.api-prefix}/swagger-ui.html'

logging:
  level:
    org.hibernate.SQL: DEBUG
