server:
  port: 8080

spring:
  application:
    name: user-service
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    operationsSorter: method
    try-it-out-enabled: true
  writer-with-order-by-keys: true

logging:
  level:
    org.hibernate.SQL: DEBUG
