server:
  port: 8081

spring:
  application:
    name: notification-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8079/eureka/
  instance:
    hostname: localhost
