server:
  port: 8080
  forward-headers-strategy: native
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
    api-prefix: ""
    fe-default-url: https://petinder-green.vercel.app/

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}${spring.application.api-prefix}/login/oauth2/code/{registrationId}"
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: openid, email, profile

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  duration: 60  # in minutes
  private:
    key: classpath:key/app.key
  public:
    key: classpath:key/app.pub

#springdoc:
#  api-docs:
#    path: '${spring.application.api-prefix}/v3/api-docs'
#  swagger-ui:
#    operationsSorter: method
#    try-it-out-enabled: true
#    path: '${spring.application.api-prefix}/swagger-ui.html'

logging:
  level:
    org:
      springframework:
        security:
          web: trace
          oauth2: info
      hibernate:
        SQL: info
