server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      forwarded:
        enabled: true
      routes:
        - id: auth-service
          uri: "http://auth-service:8080/"
          predicates:
            - Path=/auth/**
        - id: pet-service
          uri: "http://pet-service:8080/"
          predicates:
            - Path=/pet/**
        - id: user-service
          uri: "http://user-service:8080/"
          predicates:
            - Path=/user/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    try-it-out-enabled: true
    urls:
      - url: /auth/v3/api-docs
        name: Auth Service
      - url: /user/v3/api-docs
        name: User Service
      - url: /pet/v3/api-docs
        name: Pet Service

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
