server:
  port: 8082

spring:
  application:
    name: pet-service

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    operationsSorter: method
    try-it-out-enabled: true
  writer-with-order-by-keys: true

logging:
  level:
    org.hibernate.SQL: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8079/eureka/

  instance:
    hostname: localhost