services:

  #  pet-service:
  #    build:
  #      context: .
  #    env_file:
  #      - path: ./env/docker.env
  #    ports:
  #      - "127.0.0.1:8080:8080"
  #    depends_on:
  #        db:
  #          condition: service_healthy

  pet-db:
    env_file:
      - path: ./env/docker.env
    image: postgres
    restart: always
    user: postgres
    volumes:
      - pet-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pet-data:
