services:
#  user-service:
#    build:
#      context: .
#    env_file:
#      - path: ./env/docker.env
#    expose:
#      - 8080
#    depends_on:
#      user-db:
#        condition: service_healthy

  user-db:
    image: postgres:16.3
    restart: always
    env_file:
      - path: ./env/docker.env
    volumes:
      - user-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-data:
